<?php
$city = array(
    "Agadir"                => "Agadir",
    "Al Hoceima"            => "Al Hoceima",
    "Azilal"                => "Azilal",
    "Beni Mellal"           => "Beni Mellal",
    "Ben Slimane"           => "Ben Slimane",
    "Boulemane"             => "Boulemane",
    "Casablanca"            => "Casablanca",
    "Chaouen"               => "Chaouen",
    "El Jadida"             => "El Jadida",
    "El Kelaa des Sraghna"  =>"El Kelaa des Sraghna",
    "Er Rachidia"           =>"Er Rachidia",
    "Essaouira"             =>"Essaouira",
    "Fes"                   =>"Fes",
    "Figuig"                =>"Figuig",
    "Guelmim"               =>"Guelmim",
    "Ifrane"                =>"Ifrane",
    "Kenitra"               =>"Kenitra",
    "Khemisset"             =>"Khemisset",
    "Khenifra"              =>"Khenifra",
    "Khouribga"             =>"Khouribga",
    "Laayoune"              =>"Laayoune",
    "Larache"               =>"Larache",
    "Marrakech"             =>"Marrakech",
    "Meknes"                =>"Meknes",
    "Nador"                 =>"Nador",
    "Ouarzazate"            =>"Ouarzazate",
    "Oujda"                 =>"Oujda",
    "Rabat-Sale"            =>"Rabat-Sale",
    "Safi"                  =>"Safi",
    "Settat"                =>"Settat",
    "Sidi Kacem"            =>"Sidi Kacem",
    "Tangier"               =>"Tangier",
    "Tan-Tan"               =>"Tan-Tan",
    "Taounate"              =>"Taounate",
    "Taroudannt"            =>"Taroudannt",
    "Tata"                  =>"Tata",
    "Taza"                  =>"Taza",
    "Tetouan"               =>"Tetouan",
    "Tiznit"                =>"Tiznit"
);
?>

<!-- <option value="Agadir">Agadir</option>
<option value="Al Hoceima">Al Hoceima</option>
<option value="Azilal">Azilal</option>
<option value="Beni Mellal">Beni Mellal</option>
<option value="Ben Slimane">Ben Slimane</option>
<option value="Boulemane">Boulemane</option>
<option value="Casablanca">Casablanca</option>
<option value="Chaouen">Chaouen</option>
<option value="El Jadida">El Jadida</option>
<option value="El Kelaa des Sraghna">El Kelaa des Sraghna</option>
<option value="Er Rachidia">Er Rachidia</option>
<option value="Essaouira">Essaouira</option>
<option value="Fes">Fes</option>
<option value="Figuig">Figuig</option>
<option value="Guelmim">Guelmim</option>
<option value="Ifrane">Ifrane</option>
<option value="Kenitra">Kenitra</option>
<option value="Khemisset">Khemisset</option>
<option value="Khenifra">Khenifra</option>
<option value="Khouribga">Khouribga</option>
<option value="Laayoune">Laayoune</option>
<option value="Larache">Larache</option>
<option value="Marrakech">Marrakech</option>
<option value="Meknes">Meknes</option>
<option value="Nador">Nador</option>
<option value="Ouarzazate">Ouarzazate</option>
<option value="Oujda">Oujda</option>
<option value="Rabat-Sale">Rabat-Sale</option>
<option value="Safi">Safi</option>
<option value="Settat">Settat</option>
<option value="Sidi Kacem">Sidi Kacem</option>
<option value="Tangier">Tangier</option>
<option value="Tan-Tan">Tan-Tan</option>
<option value="Taounate">Taounate</option>
<option value="Taroudannt">Taroudannt</option>
<option value="Tata">Tata</option>
<option value="Taza">Taza</option>
<option value="Tetouan">Tetouan</option>
<option value="Tiznit">Tiznit</option> -->